#!/bin/bash
SIZE=$(stat -c '%s' firmware.bin)
HASH=$( sha256sum firmware.bin | cut -f 1 -d ' ')

echo $HASH $SIZE | openssl rsautl -sign -inkey private.pem > firmware.sig
cat firmware.bin >> firmware.sig
